version: '3.1'
services:
  scrde-app:
    build:
       context: ./
       dockerfile: Dockerfile
    ports:
       - "80:3838"
    restart: unless-stopped
    container_name: scrde_container
    image: scrde_image
    stdin_open: true
    networks:
      - scrde-networks
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    networks:
      - scrde-networks
    volumes:
      - ./db:/data/db
networks:
  scrde-networks:
    driver: bridge
