# -------------------------------------------------
# --              FRAMEWORK server.R             --
# -------------------------------------------------
# NOTEs:                                         --
# Program code goes in "program" directory files --
# -------------------------------------------------
# *****        DO NOT EDIT THIS FILE       ***** --
# -------------------------------------------------
user <- unname(Sys.info()["user"])
if (user == "shiny") {
  
  # Set library locations
  .libPaths(c(
    "/home/shiny/R/x86_64-pc-linux-gnu-library/3.6"
  )
  )
  
}
options(shiny.sanitize.errors = FALSE)
library(shinydashboard)

periscope:::fw_reset_app_options()

source(paste("program", "ui_sidebar.R", sep = .Platform$file.sep),
       local = TRUE)
source(paste("program", "ui_body.R", sep = .Platform$file.sep),
       local = TRUE)


dashboardPage(periscope:::fw_create_header(),
              periscope:::fw_create_sidebar(),
              periscope:::fw_create_body())
